# ===================================================================
# CONFIGURACIÓN DE LA BASE DE DATOS (MySQL)
# ===================================================================
# Ruta de conexión: local, puerto 3306 y el nombre de tu esquema médico
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_medica_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true

# Credenciales de tu servidor local de MySQL Workbench
spring.datasource.username=root
spring.datasource.password=root

# El Driver que gestiona la comunicación
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===================================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===================================================================
# Muestra en la consola de VS Code las consultas SQL reales que se ejecuten (Muy útil para debugear)
spring.jpa.show-sql=true

# Formatea el SQL en consola para que sea fácil de leer por el desarrollador
spring.jpa.properties.hibernate.format_sql=true

# Comportamiento de la base de datos al arrancar:
# 'update' verifica tus clases Java y crea/actualiza las tablas automáticamente sin borrar los datos existentes.
spring.jpa.hibernate.ddl-auto=update

# Dialecto específico para optimizar las consultas según tu versión de MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Desactivar la seguridad básica automática de Spring Boot
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration